


//CONSTANTES SE ESCRIBEN EN MAYUSCULAS

var LIMITE=45;
var LIMITE_TOTAL=78;


//EL PUNTO Y COMPA SE COLOCA CUANDO UNA SENTENCIA SE VA EJECUTAR o en una declaración
// LA COMA SE COLOCA PARA SEPARAR SEPARAR PARÁMETROS